name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        source venv/bin/activate
        pytest

    - name: Run flake8 linter
      run: |
        source venv/bin/activate
        flake8
